openapi: 3.0.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of contacts app

tags:
  - name: auth
    description: Authentication endpoints
  - name: contacts
    description: Contacts management
 
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-a7nh.onrender.com

      

paths:
  /contacts:
    get:
      $ref: './paths/contacts/get.yaml'
    post:
      $ref: './paths/contacts/post.yaml'

  /contacts/{id}:
    get:
      $ref: './paths/contacts/{id}/get.yaml'
    patch:
      $ref: './paths/contacts/{id}/patch.yaml'
    delete:
      $ref: './paths/contacts/{id}/delete.yaml'

  /auth/register:
    post:
      $ref: './paths/auth/login.yaml'
  /auth/login:
    post:
      $ref: './paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: './paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: './paths/auth/refresh.yaml'
  /auth/send-reset-email:
    post:
      $ref: './paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: './paths/auth/reset-pwd.yaml'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
